# Generated by Django 4.0.1 on 2022-01-23 21:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('todo', '0002_delete_todo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Todo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30)),
                ('content', models.TextField()),
                ('add_date', models.DateTimeField(verbose_name='date created')),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
