# Generated by Django 4.0.1 on 2022-01-23 22:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0003_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todo',
            name='updated',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
