# Generated by Django 4.0.1 on 2022-01-23 22:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0004_alter_todo_updated'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todo',
            name='add_date',
            field=models.DateTimeField(auto_now=True, verbose_name='date created'),
        ),
    ]
