# Generated by Django 4.0.1 on 2022-02-04 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0008_alter_todo_updated'),
    ]

    operations = [
        migrations.AddField(
            model_name='todo',
            name='future_date',
            field=models.DateTimeField(null=True),
        ),
    ]
