# Generated by Django 4.0.1 on 2022-02-07 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0009_todo_future_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='todo',
            name='slug',
            field=models.SlugField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='todo',
            name='future_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
