# Generated by Django 4.0.1 on 2022-02-07 10:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0010_todo_slug_alter_todo_future_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='todo',
            name='future_date',
        ),
    ]
