# Generated by Django 4.0.1 on 2022-02-18 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0013_todo_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='todo',
            name='completed',
            field=models.BooleanField(default=False),
        ),
    ]
