# Generated by Django 4.0.1 on 2022-02-19 10:55

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0015_remove_todo_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todo',
            name='title',
            field=models.CharField(max_length=30, validators=[django.core.validators.MaxLengthValidator(30, message='Title cannot exceed 30 characters.')]),
        ),
    ]
